// USERS
export const GET_USERDATA = 'GET_USERDATA';
export const GET_ALLUSERS = 'GET_ALLUSERS';

// ERROR HANDLING
export const CREATE_MESSAGE = 'CREATE_MESSAGE';
export const GET_ERRORS = 'GET_ERRORS';
export const AUTH_ERROR = 'AUTH_ERROR';

// AUTH
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const CONVERT_TOKEN = 'CONVERT_TOKEN';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

// CATEGORIES
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_SUBCATEGORIES = 'GET_SUBCATEGORIES';
export const GET_SERVICES = 'GET_SERVICES';

// SERVICES
export const GET_SERVICE = 'GET_SERVICE';
export const CREATE_SERVICE = 'CREATE_SERVICE';
export const DELETE_SERVICE = 'DELETE_SERVICE';
export const UPDATE_SERVICE = 'UPDATE_SERVICE';
export const ADD_SERVICE_REVIEW = 'ADD_SERVICE_REVIEW';
export const CREATE_SERVICE_FAILURE = 'CREATE_SERVICE_FAILURE';
export const DELETE_SERVICE_FAILURE = 'DELETE_SERVICE_FAILURE';

// LOCATION
export const CREATE_LOCATION = 'CREATE_LOCATION';
export const DELETE_LOCATION = 'DELETE_LOCATION';
export const CREATE_LOCATION_FAILURE = 'CREATE_LOCATION_FAILURE';

// CONTRACTS
export const GET_CONTRACTS = 'GET_CONTRACTS';
export const CREATE_CONTRACT = 'CREATE_CONTRACT';
export const DELETE_CONTRACT = 'DELETE_CONTRACT';
export const UPDATE_CONTRACT = 'UPDATE_CONTRACT';
export const ADD_CONTRACT_COMMENT = 'ADD_CONTRACT_COMMENT';